// Generated by ts-to-zod
import { z } from 'zod';

export const unitSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  life: z.number()
});

export const unitPropsSchema = unitSchema.omit({ id: true });
